---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp-mongodb
  namespace: loginapp
spec:
  selector:
    matchLabels:
      app: loginapp-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: loginapp-mongodb
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: loginapp-secrets
              key: MONGO_INITDB_ROOT_USERNAME
              optional: false
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: loginapp-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
              optional: false
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "50m"
            memory: "500Mi"
          limits:
            cpu: "80m"
            memory: "600Mi"
        volumeMounts:
        - name: loginapp-mongodb
          mountPath: /etc/mongo
      volumes:
      - name: loginapp-mongodb
        persistentVolumeClaim:
          claimName: loginapp-mongodb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loginapp-mongodb-pvc
  namespace: loginapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: loginapp-mongodb-svc
  namespace: loginapp
spec:
  selector:
    app: loginapp-mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loginapp-mongodb-pvc
  namespace: loginapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 20Gi
